version: 0.2

env:
  variables:
    TF_VERSION: "0.11.13"

phases:

  install:
    commands:
      - echo Downloading Terraform
      - cd /usr/bin
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - terraform init -input=false
      - zip sns_slack_notification_payload.zip sns-slack-integration/sns_slack_integration.py
      - aws s3 cp s3://$PLAN_BUCKET/tfplan tfplan
      - terraform apply -input=false tfplan

  post_build:
    commands:
      - echo "terraform plan completed on `date`"
